apiVersion: batch/v1
kind: Job
metadata:
  name: otus-hw-init-db-job
spec:
  template:
    spec:
      initContainers:
        - name: check-db-ready
          image: postgres:latest
          command:
            - sh
            - "-c"
            - |
              until pg_isready -h $DB_HOST  -p  $DB_PORT;
              do echo waiting for database; sleep 0.1; done;
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: otus-hw-secret
                  key: db.host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: otus-hw-secret
                  key: db.port
      containers:
      - name: otus-hw
        image: krtvand/otus-hw:2.11
        imagePullPolicy: IfNotPresent
        command: ["init_db"]
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: otus-hw-secret
                key: db.user
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: otus-hw-secret
                key: db.pass
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: otus-hw-secret
                key: db.name
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: otus-hw-secret
                key: db.host
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: otus-hw-secret
                key: db.port

      restartPolicy: Never
  backoffLimit: 0
