apiVersion: apps/v1
kind: Deployment
metadata:
  name: otus-hw-deployment
  labels:
    app: otus-hw
spec:
  replicas: 3
  selector:
    matchLabels:
      app: otus-hw
  template:
    metadata:
      labels:
        app: otus-hw
    spec:
      initContainers:
        - name: check-db-ready
          image: postgres:latest
          command:
            - sh
            - "-c"
            - |
              until pg_isready -h $DB_HOST  -p  $DB_PORT;
              do echo waiting for database; sleep 1; done;
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: otus-hw-secret
                  key: db.host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: otus-hw-secret
                  key: db.port

      containers:
      - name: otus-hw
        image: krtvand/otus-hw:2.9
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8000
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: otus-hw-secret
                key: db.user
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: otus-hw-secret
                key: db.pass
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: otus-hw-secret
                key: db.name
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: otus-hw-secret
                key: db.host
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: otus-hw-secret
                key: db.port
          - name: HOST
            valueFrom:
              configMapKeyRef:
                name: otus-hw-config-map
                key: hello-app.host
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: otus-hw-config-map
                key: hello-app.port

