apiVersion: batch/v1
kind: Job
metadata:
  name: otus-hw-init-db-job
spec:
  template:
    spec:
      containers:
      - name: otus-hw
        image: krtvand/otus-hw:2.6
        command: ["init_db"]
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: otus-hw-secret
                key: db.user
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: otus-hw-secret
                key: db.pass
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: otus-hw-secret
                key: db.name
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: otus-hw-secret
                key: db.host
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: otus-hw-secret
                key: db.port

      restartPolicy: Never
  backoffLimit: 0
